config/routes.rb
Rails.application.routes.draw do

  get '/welcome/loggedout', to: 'welcome#loggedout', as: 'loggedout'
  get '/welcome/about', to: 'welcome#about', as: 'about'
  get '/login', to:'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#delete'

  resources :users
  resources :posts do
    resources :comments, shallow: true, only: [:create, :destroy]
  end

  resources :conversations do
    resources :messages
  end

  root 'welcome#index', as: 'welcome'

  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :user
	belongs_to :post
end

app/models/conversation.rb
class Conversation < ActiveRecord::Base
	belongs_to :sender, foreign_key: :sender_id, class_name: 'User'
  belongs_to :recipient, foreign_key: :recipient_id, class_name: 'User'

  has_many :messages, dependent: :destroy

  validates_uniqueness_of :sender_id, scope: :recipient_id #ensures that the sender_id and the recipient_id are always unique so that we only have unique conversations in our application

  scope :involving, -> (user) do
    where("conversations.sender_id =? OR conversations.recipient_id =?",user.id,user.id)
  end
  #help us retrieve all conversations of the currently logged-in user

  scope :between, -> (sender_id,recipient_id) do
    where("(conversations.sender_id = ? AND conversations.recipient_id =?) OR (conversations.sender_id = ? AND conversations.recipient_id =?)", sender_id,recipient_id, recipient_id, sender_id)
  end
  #check if a conversation exists between any given two users before we create the conversation
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :conversation
  belongs_to :user

  validates_presence_of :body, :conversation_id, :user_id

 
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
	has_many	:comments, dependent: :destroy
end

app/models/user.rb
class User < ActiveRecord::Base

	validates :username, length:  {minimum: 4, maximum: 30}
	has_many	:posts, dependent: :destroy
	has_many	:comments
	validates_uniqueness_of	:email
	validates :email, confirmation: true, presence: true
	validates :password, confirmation: true, presence: true
	validates_presence_of :username, :fname, :lname, :email, :bio, :password, :city, :state, :country


	def self.find_by_email(email)
		User.where("lower(email) = ?", email.downcase).first
	end


  def self.find_by_username(username)
      User.where("lower(username) = ?", username.downcase).first
  end

  has_many :conversations, foreign_key: :sender_id
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  private
	  def current_user
	   	session[:user_id] ? User.find(session[:user_id]) : nil
	   	
	   	# if session[:user_id]
	   	# 	User.find(session[:user_id])
	   	# else 
	   	# 	nil
	   	# end
	  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def show
    @comments = Comment.all
  end

  def new

  end

  def edit
  end

  def create
    @comment = Comment.create(params.require(:comment).permit(:comment_body).merge(user: current_user, post_id: params[:post_id]))
    redirect_to @comment.post
  end

  def destroy
  end

  
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController

	layout false

  def create
    if Conversation.between(params[:sender_id],params[:recipient_id]).present?
      @conversation = Conversation.between(params[:sender_id],params[:recipient_id]).first
    else
      @conversation = Conversation.create!(conversation_params)
    end

    render json: { conversation_id: @conversation.id }
  end

  def show
    @conversation = Conversation.find(params[:id])
    @reciever = interlocutor(@conversation)
    @messages = @conversation.messages
    @message = Message.new
  end

  private

  def conversation_params
    params.require(:conversation).permit(:sender_id, :recipient_id)
  end

  def interlocutor(conversation)
    current_user == conversation.recipient ? conversation.sender : conversation.recipient
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

	def create
		@conversation = Conversation.find(params[:conversation_id])
		@message = @conversation.messages.build(message_params)
		@message.user_id = current_user.id
		@message.save!

		@path = conversation_path(@conversation)
	end

  private

  def message_params
    params.require(:message).permit(:body)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
before_action :set_post, only: [:show, :edit, :update, :destroy]

  def index
    @posts = Post.all.order('created_at DESC')
  end


  def new
    if current_user
      @post = Post.new
    else
      flash[:notice]="Please sign in order to post"
      redirect_to login_path
    end
  end

  def show
    @comment = Comment.new
  end

  # def edit
  #   @post = Post.find(params[:id])
  #   redirect_to @posts_path, 
  #   flash[:notice] = "Your post was updated"
  #   else
  #     render :edit
  # end

  def create
    @post = Post.create(post_params)
    #or 
    #@post = Post.create(:post_body: params[:post][:post_body], session[:user_id])
    flash[:notice] = "Your post was created. Thank you for sharing."
    redirect_to posts_path 
  end

  def update
    if current_user
      @post.update(post_params)
    redirect_to posts_path, notice: "Your post was updated"
    else
      render :edit
    end
  end


  def destroy
    if current_user
        @post = Post.find(params[:id])
        @post.destroy
        flash[:notice] = "Your post has been deleted."
        redirect_to posts_path
    else
     redirect_to '/'
    end
  end


  private

  def post_params
    params.require(:post).permit(:title, :post_body).merge(user: current_user)
  end

  def set_post
    @post = Post.find(params[:id])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	@user = User.find_by(email: params[:email])
  	if @user and @user.password == params[:password]
  		session[:user_id] = @user.id
  		flash[:notice] = "You are logged in!"
  		redirect_to @user
  	else
  		flash[:notice] = "Incorrect email or password, try again!"
  		render :new #new.html.erb with render 'form'
	end
end

  def delete  #log out
  	session[:user_id] = nil
  	flash[:notice] = "You are logged out. See you soon!"
  	redirect_to loggedout_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 
#show the list of all users
  def index
    @users = User.all
  end

  def edit
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def create
  	@user = User.new(user_params)
      if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user), notice: "New account created."
      else
      flash[:alert] = "There was a problem creating your account, please try again."
      redirect_to new_user_path
      end
  end
  
  def update 
    @user = User.find(params[:id])
    @user.update(user_params)
    flash[:notice] = "Your profile has been successfully updated."  
    redirect_to user_path(@user)
  end
    
  def destroy
    @user = User.find(params[:id])
    if  @user.destroy
        session[:user_id] = nil
        flash[:notice] = "Your profile has been deleted."
    else
        flash[:alert] = "There was a problem deleting your profile."
    end
    redirect_to loggedout_path
  end
    
end

private

def user_params
  params.require(:user).permit(:username, :fname, :lname, :bio, :email, :password, :city, :state, :country)
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  	# render :layout => false
  	
  end

  def contact
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def current_user
		 session[:user_id] ? User.find(session[:user_id]) : nil
	end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
  def self_or_other(message)
    message.user == current_user ? "self" : "other"
  end

  def message_interlocutor(message)
    message.user == message.conversation.sender ? message.conversation.sender : message.conversation.recipient
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
	def current_user
		 session[:user_id] ? User.find(session[:user_id]) : nil
	end
end

app/views/comments/show.html.erb
<h1>Comments#show</h1>
<p>Find me in app/views/comments/show.html.erb</p>

app/views/conversations/show.html.erb
<div class="chatboxhead">
  <div class="chatboxtitle">
    <i class="fa fa-comments"></i>

    <h1><%= @reciever.name %> </h1>
  </div>
  <div class="chatboxoptions">
    <%= link_to "<i class='fa  fa-minus'></i> ".html_safe, "#", class: "toggleChatBox", "data-cid" => @conversation.id %>
    &nbsp;&nbsp;
    <%= link_to "<i class='fa  fa-times'></i> ".html_safe, "#", class: "closeChat", "data-cid" => @conversation.id %>
  </div>
  <br clear="all"/>
</div>
<div class="chatboxcontent">
  <% if @messages.any? %>
      <%= render @messages %>
  <% end %>
</div>
<div class="chatboxinput">
  <%= form_for([@conversation, @message], :remote => true, :html => {id: "conversation_form_#{@conversation.id}"}) do |f| %>
      <%= f.text_area :body, class: "chatboxtextarea", "data-cid" => @conversation.id %>
  <% end %>
</div>

<%= subscribe_to conversation_path(@conversation) %>

app/views/messages/_message.html.erb
<li class="<%=  self_or_other(message) %>">
  <div class="avatar">
    <img src="http://placehold.it/50x50" />
  </div>
  <div class="chatboxmessagecontent">
    <p><%= message.body %></p>
    <time datetime="<%= message.created_at %>" title="<%= message.created_at.strftime("%d %b  %Y at %I:%M%p") %>">
      <%= message_interlocutor(message).name %> • <%= message.created_at.strftime("%H:%M %p") %>
    </time>
  </div>
</li>

app/views/messages/create.js.erb
<% publish_to @path do %>
    var id = "<%= @conversation.id %>";
    var chatbox = $("#chatbox_" + id + " .chatboxcontent");
    var sender_id = "<%= @message.user.id %>";
    var reciever_id = $('meta[name=user-id]').attr("content");

    chatbox.append("<%= j render( partial: @message ) %>");
    chatbox.scrollTop(chatbox[0].scrollHeight);

    if(sender_id != reciever_id){
    	chatBox.chatWith(id);
        chatbox.children().last().removeClass("self").addClass("other");        
    	chatbox.scrollTop(chatbox[0].scrollHeight);
        chatBox.notify();
    }
<% end %>

app/views/posts/_errors.html.erb
<% if @post.errors.full_messages.any? %>
		<ul><% @post.errors.full_message.each do |error| %>
			<li style="color: red bold;"><%= error %></li>
			<% end %>
		</ul>
	<% end %>

app/views/posts/_form.html.erb
<% content_for :use_posts do %>
	
	<div class="edit_field">
		<% if current_user %>
			<h4>Enter and submit a post below:</h4>
				<%= form_for @post do |f| %>
					<%= f.text_field :title, placeholder: "Enter post title" %><br>
					<%= f.text_area :post_body, placeholder: "Enter post body" %><br>
					<%= f.submit :class => 'submit'%>
					<br>
					<p class="cancel"><%= link_to 'Cancel your post', posts_path %></p>
			
				<% end %>
		<% else %>
			<h5><%= link_to 'Login', login_path %> to comment.</h5>
		<% end %>
	</div>
<% end %>

app/views/posts/edit.html.erb
<h1>Please edit your post below</h1>
<% content_for :use_posts do %>
<%= render 'errors' %>
<%= render 'form' %>
<% end %>

app/views/posts/index.html.erb
<% content_for :use_posts do %>

<h1>Recent Posts</h1>
<div class="table">
<table>
  <tr>
	<td class="thead_title">Title</td>
	<td class="thead_body">Post body</td>
	<td class="thead_username">Username</td>
	<td class="thead_date">Posted on</td>
	</tr>	
	<% @posts.each do |post| %>
  <tr>
    <td class="post_list_title"><%= link_to post.title.truncate(60), post_path(post.id) %></td>
    <td class="post_list_body"><%= post.post_body.truncate(60) %></td>

    <td class="post_list_username"><%= post.user.username %></td>		
    <td class="post_list_date"><%= post.created_at.to_date.strftime("%m/%d/%Y") %></td>
    <% end %>
  </tr>
</table>
</div>
<% if current_user %>
<p class="enter_post"><%=link_to "Click here",  new_post_path %> to Enter a New Post</p>

<% else %>
    <p class ="login_post"> <%= link_to 'Click here', login_path %> to Log in or <%= link_to 'Click here', new_user_path %> to Register to post or comment.</p><br>
<% end %>


<% end -%>

app/views/posts/new.html.erb
<% content_for :use_posts do %>
<h1>Wed Log Posts!</h1>

<%= render 'errors' %>

<h1><%= @post.title %></h1>
<p><% @post.post_body %></p>
<hr>

<%= render 'form' %>

<% end %>

app/views/posts/show.html.erb
<% content_for :use_posts do %>

<%= render 'errors' %>

<div class="post_area">
	<p class="post_title">{ <%= @post.title %> }</h1>
	<p class="post_body"><%= @post.post_body %></p>
	  <% if current_user %>
			<p class="edit"><%= link_to 'EDIT', edit_post_path %></p>
			<p class="delete"><%= link_to 'DELETE', post_path(@post.id), method: :delete, data: {confirm: "Are you sure you wish to delete your post?"} %></p>
	  <% end %>
				<!-- <h3><rubytag= time_ago_in_words(post_body.created_at) rubytag></h3> -->
				
				

<% @post.comments.each do |comment| %>
	<p class="comment_body"><%= comment.comment_body %></p>
	<p class="comment_username">By <%= comment.user.username %></p>
<%end %>

	<% if current_user %>
		<h4>Post a comment below:</h4>
				<%= form_for [@post, @comment] do |f| %>
				<%= f.text_area :comment_body, placeholder: "Enter comment here" %><br>
			<%= f.submit :class => 'submit' %>

			<br>
			<p class="cancel"><%= link_to 'Cancel your comment', posts_path%></p>
	<% end %>
	<% else %>
		<p class="loginMsg"><%= link_to 'Login', login_path %> to post or comment.</p>
<% end %>
</div>

<% end %>

app/views/users/_form.html.erb
	<div id="signup_form">
		<%= form_for @user do |f| %>

			<p>
				<%= f.text_field :username, placeholder: 'Username', :class => 'text_field' %>
			</p>
			<p>
				<%= f.text_field :fname, placeholder: 'First Name', :class => 'text_field' %>
			</p>
			<p>
				<%= f.text_field :lname, placeholder: 'Last Name', :class => 'text_field' %>
			</p>
			<p>
				<%= f.text_field :bio, placeholder: 'Bio', :class => 'text_field' %>
			</p>
			<p>
				<%= f.email_field :email, placeholder: 'E-mail', :class => 'text_field' %>
			</p>
			<p>
				<%= f.email_field :email_confirmation, placeholder: 'Please re-enter your e-mail', :class => 'text_field' %>
			</p>
			<p>
				<%= f.password_field :password, placeholder: 'Password', :class => 'text_field' %>
			</p>
			<p>
				<%= f.password_field :password_confirmation, placeholder: 'Please re-enter your password', :class => 'text_field' %>
			</p>
			<p>
				<%= f.text_field :city, placeholder: 'City', :class => 'text_field' %>
			</p>
			<p>
				<%= f.text_field :state, placeholder: 'State/Province', :class => 'text_field' %>
			</p>
			<p>
				<%= f.text_field :country, placeholder: 'Country', :class => 'text_field' %>
			</p>
			<br>
			<p><%= f.submit :class => 'submit', :value => 'Sign Up' %></p>	
		<% end %>
	</div>

app/views/users/_message_html.erb
<% @users.each_with_index do |user, index| %>
    <tr>
      <td><%= index +=1 %></td>
      <td><%= user.name %></td>
      <td>
        <%= link_to "Send Message", "#", class: "btn btn-success btn-xs start-conversation",
                    "data-sid" => current_user.id, "data-rip" => user.id %>
      </td>
    </tr>
<% end %>

app/views/users/edit.html.erb
<h1>Edit your Wed Log profile</h1>
<% content_for :use_login do %>

<%= render 'form' %>

<% end -%>

app/views/users/index.html.erb
<h1>Wedlog Members</h1>
<% content_for :use_user do %>

<ul class="member_list">
	<% @users.each do |user| %>	
		<li class="user_list"><%= link_to user.username, user_path(user.id)%></li>

<!-- first argument: what you want to call the route, second argument: where do you want the route to go, in this case, the link will be shown as username and will link to user_path(User's page) -->
	<% end %>
</ul>
<%= render 'message' %>

<% end %>

app/views/users/new.html.erb
<h1>Sign Up Below</h1>
<% content_for :use_login do %>

<%= render 'form' %>
<% end %>

app/views/users/show.html.erb
<% content_for :use_user do %>


<% if current_user and current_user == @user %>

<p class="flash_notice">Good to see you again, <%= @user.username %>!</p>
<h3><%= "Your Profile Details" %>
<p class="loginprofile"><%= @user.email %></p>
<p><%= @user.bio %></p>
<p><%= @user.city  + ", " + @user.state + ", " + @user.country %></p>
<p><%= link_to 'Delete Profile', user_path(@user.id), method: :delete, data: {confirm: "Are you sure you wish to delete your profile?"} %></p>
<p><%= link_to "Edit Profile", edit_user_path(@user.id) %></p>

<% else %>
<div class="user_page">

	<div class="user_info">
		<p class="username" style="text-align: center"><%= "You are viewing "  + @user.username + "'s" " profile."%></p>
		<h3>Name:</h3>

		<p class="userinfo"><%= @user.fname  + " " + @user.lname %></p>

		<h3>Email Address:</h3>
		<p class="userinfo"><%= @user.email %></p>

		<h3>Bio:</h3>

		<p class="userinfo"><%= @user.bio %></p>

		<h3> City, State/Province, County:</h3>

		<p class="userinfo"><%= @user.city  + ", " + @user.state + ", " + @user.country %></p>
		<% end %>
	</div>
	<!-- <div class="line"></div> -->

	<div class="user_post">
		<h3><%= @user.username %>'s Posts</h3>
			<ul style="list-style: none;">
				<% @user.posts.each do |post| %>
					<li class="user_post_list" style="text-decoration: none;"><%= link_to post.title, post %></li>
				<% end %>
				<% if @user.posts.each do |post| %>
				    <%= post.post_body %>
				    <% end.empty? %>
		       <p class="userinfo">You have no posts.</p>
				<% end %>
			</ul>

<p class="back"><%= link_to 'Back to Users', users_path %></p>
	</div>
	</div>
<% end %>

app/views/welcome/index.html.erb
<% content_for :use_welcome do %>
<!-- 	<h1>Hello</h1>
	<p>This is a welcome page</p> -->

  <div id="slides">
  	<img class="top-image" src="/assets/wedding-top.png"  alt="Engagement/Wedding" />

  </div>
  
 <% end -%>
<!-- 
<div id="signup"><h1> Welcome to the H&M Wedding Blog</div>

<div id="login">Nothing here yet</div>
 -->

app/views/welcome/loggedout.html.erb
<% content_for :use_welcome do %>
<p class="logoutmsg">Thank you for visiting Wedlog</p>
<% end %>